/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package edu.uthouston.sbmi.hootation.ui;

import edu.uthouston.sbmi.hootation.llmenrichment.util.LLMConfiguration;
import javax.swing.JFrame;

/**
 *
 * @author mac
 */
public class FactCheckingDialog extends javax.swing.JDialog {
    
    private String instructions_fact_checking = "Ensure the placeholder [statement] is in the prompt below.";
    
    private String instructions_enrichment = "Ensure the placeholder [axiom] and [axiom_type] is in the prompt below.";
    
    private boolean isFactCheckDialog = true;

    private HootationUI hootation;
    /**
     * Creates new form FactCheckingDialog
     */
    public FactCheckingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hootation = (HootationUI) parent;
    }
    
    public void setInstructionsForFactChecking(String default_prompt){
        this.txtInstructions.setText( instructions_fact_checking);
        this.setTitle("Fact Checking Prompt");
        this.txtPrompt.setText(default_prompt);
        isFactCheckDialog = true;
    }
    
    public String getPromptText(){
        return txtPrompt.getText();
    }
    
    public void setInstructionsForEnrichment(String default_prompt){
        this.txtInstructions.setText(instructions_enrichment);
        this.setTitle("LLM Enrichment Prompt");
        this.txtPrompt.setText(default_prompt);
        isFactCheckDialog = false;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInstructions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrompt = new javax.swing.JTextPane();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRestoreDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtInstructions.setText("Ensure the placeholder [statement] is in the prompt below");

        jScrollPane1.setViewportView(txtPrompt);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRestoreDefault.setText("Restore Default");
        btnRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestoreDefault)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel)
                    .addComponent(btnRestoreDefault))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
       
        sendUserCustomPrompts();
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void sendUserCustomPrompts(){
        if(isFactCheckDialog){
            hootation.setFactCheckingPrompt(txtPrompt.getText());
        }
        else{
            hootation.setAxiomTranslationPrompt(txtPrompt.getText());
        }
        
    }
    
    private void restoreDefaultPrompt(){
        if(isFactCheckDialog){
            txtPrompt.setText(LLMConfiguration.getInstance().getPROMPT_FACT_CHECK());
        }
        else{
            txtPrompt.setText(LLMConfiguration.getInstance().getPROMPT_TRANSLATION());
        }
        
        sendUserCustomPrompts();
    }
    
    private void btnRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreDefaultActionPerformed
        // TODO add your handling code here:
        
        
        restoreDefaultPrompt();
    }//GEN-LAST:event_btnRestoreDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactCheckingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactCheckingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactCheckingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactCheckingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FactCheckingDialog dialog = new FactCheckingDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRestoreDefault;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtInstructions;
    private javax.swing.JTextPane txtPrompt;
    // End of variables declaration//GEN-END:variables
}
