/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.uthouston.sbmi.hootation.ui;


import com.formdev.flatlaf.FlatLightLaf;
import edu.uthouston.sbmi.hootation.GenerateStatements;

import edu.utmb.semantic.llmenrichment.util.LLMConfiguration;
import java.awt.FileDialog;
import java.io.File;
import java.util.ArrayList;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mac
 */
public class HootationUI extends javax.swing.JFrame {
    
    private  DefaultListModel llm_list = new DefaultListModel();
    private Map<String, String> llmList;

    /**
     * Creates new form HootationUI
     */
    public HootationUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputOptions = new javax.swing.ButtonGroup();
        modeldownloadOption = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelHootation = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectButtonFromMain = new javax.swing.JButton();
        pathTextFromMain = new javax.swing.JTextField();
        saveToButtonFromMain = new javax.swing.JButton();
        pathTextExportFromMain = new javax.swing.JTextField();
        csvOption = new javax.swing.JRadioButton();
        excelOption = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        ckLLM = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        llmPanel = new javax.swing.JPanel();
        ckLLMRefinement = new javax.swing.JCheckBox();
        ckLLMFactChecking = new javax.swing.JCheckBox();
        panelLLMDownload = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstLLM = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        panelLLMConfiguration = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputPanel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Select Ontology Artifact");

        selectButtonFromMain.setText("Select File");
        selectButtonFromMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonFromMainActionPerformed(evt);
            }
        });

        pathTextFromMain.setEditable(false);
        pathTextFromMain.setText("[Path to ontology file]");

        saveToButtonFromMain.setText("Save To");
        saveToButtonFromMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToButtonFromMainActionPerformed(evt);
            }
        });

        pathTextExportFromMain.setEditable(false);
        pathTextExportFromMain.setText("[Path to export file]");

        outputOptions.add(csvOption);
        csvOption.setSelected(true);
        csvOption.setText("CSV (.csv)");
        csvOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvOptionActionPerformed(evt);
            }
        });

        outputOptions.add(excelOption);
        excelOption.setText("Excel (.xlsx)");
        excelOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(selectButtonFromMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathTextFromMain, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveToButtonFromMain, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csvOption))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excelOption)
                            .addComponent(pathTextExportFromMain))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectButtonFromMain)
                    .addComponent(pathTextFromMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csvOption)
                    .addComponent(excelOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveToButtonFromMain)
                    .addComponent(pathTextExportFromMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setText("Generate Translation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ckLLM.setText("LLM enhancement (Optional, Experimental)");
        ckLLM.setName("ckLLM"); // NOI18N
        ckLLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckLLMActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jLabel7.setText("N.B. Ensure you downloaded a LLM model. Refer to LLM tabs for configuration");

        llmPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ckLLMRefinement.setText("Provide LLM refinement of the translation");
        ckLLMRefinement.setEnabled(false);

        ckLLMFactChecking.setText("Provide basic fact checking of the statements");
        ckLLMFactChecking.setEnabled(false);

        javax.swing.GroupLayout llmPanelLayout = new javax.swing.GroupLayout(llmPanel);
        llmPanel.setLayout(llmPanelLayout);
        llmPanelLayout.setHorizontalGroup(
            llmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(llmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckLLMRefinement)
                    .addComponent(ckLLMFactChecking))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        llmPanelLayout.setVerticalGroup(
            llmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckLLMRefinement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckLLMFactChecking)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHootationLayout = new javax.swing.GroupLayout(panelHootation);
        panelHootation.setLayout(panelHootationLayout);
        panelHootationLayout.setHorizontalGroup(
            panelHootationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHootationLayout.createSequentialGroup()
                .addGroup(panelHootationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHootationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelHootationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckLLM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelHootationLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelHootationLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(llmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHootationLayout.setVerticalGroup(
            panelHootationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHootationLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckLLM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(llmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hootation", panelHootation);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Choice of the Model to Download:");

        jButton2.setText("Save Model To");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelSavePathActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("[Model save path]");

        jButton3.setText("Download");

        lstLLM.setModel(llm_list);
        jScrollPane2.setViewportView(lstLLM);

        jButton9.setText("Add URL for another model");

        jButton10.setText("Remove URL for a model");

        javax.swing.GroupLayout panelLLMDownloadLayout = new javax.swing.GroupLayout(panelLLMDownload);
        panelLLMDownload.setLayout(panelLLMDownloadLayout);
        panelLLMDownloadLayout.setHorizontalGroup(
            panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2)
                    .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                        .addGroup(panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        panelLLMDownloadLayout.setVerticalGroup(
            panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLLMDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLLMDownloadLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)))
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LLM Download", panelLLMDownload);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Model Parameter Set Up:");

        jButton4.setText("Select Model");

        jButton5.setText("Select Ontology");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("[Selected Model Path]");

        jTextField3.setEditable(false);
        jTextField3.setText("[Selected Ontology Path]");

        jLabel4.setText("GPU Layers:");

        jTextField4.setText("[Enter]");

        jLabel5.setText("Thread Number:");

        jTextField5.setText("[Enter]");

        jLabel6.setText("Prediction Length:");

        jTextField6.setText("[Enter]");

        jButton8.setText("Select Result Save Path");

        jTextField7.setEditable(false);
        jTextField7.setText("[Selected Result Path]");

        javax.swing.GroupLayout panelLLMConfigurationLayout = new javax.swing.GroupLayout(panelLLMConfiguration);
        panelLLMConfiguration.setLayout(panelLLMConfigurationLayout);
        panelLLMConfigurationLayout.setHorizontalGroup(
            panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                            .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addGap(19, 19, 19)
                            .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField7)))
                    .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        panelLLMConfigurationLayout.setVerticalGroup(
            panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLLMConfigurationLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLLMConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LLM Configuration", panelLLMConfiguration);

        outputPanel.setColumns(20);
        outputPanel.setRows(5);
        jScrollPane1.setViewportView(outputPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excelOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excelOptionActionPerformed

    private void selectButtonFromMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonFromMainActionPerformed
        // TODO add your handling code here:
        
        FileDialog filedialog = new FileDialog(this, "Choose a location to save", FileDialog.LOAD);
        filedialog.setVisible(true);
        String filePath = filedialog.getDirectory()+ filedialog.getFile();
        //GenerateStatements gs = GenerateStatements.getInstance();
       
        System.out.println(filePath);
        
        this.pathTextFromMain.setText(filePath);
        
        
        
    }//GEN-LAST:event_selectButtonFromMainActionPerformed

    private void saveToButtonFromMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToButtonFromMainActionPerformed
        // TODO add your handling code here:
        
        FileDialog filedialog = new FileDialog(this, "Choose a location to save", FileDialog.SAVE);
        filedialog.setVisible(true);
        //filedialog.setFile("");
        
        //String savePath = filedialog.getDirectory()+filedialog.getFile();
        
        String fileName = filedialog.getFile();
        if(csvOption.isSelected()){
            fileName = fileName + ".csv";
        }
        else{
            fileName = fileName + ".xlsx";
        }
        
        String savePath = filedialog.getDirectory()+fileName;
        
        this.pathTextExportFromMain.setText(savePath);
    }//GEN-LAST:event_saveToButtonFromMainActionPerformed

    private void csvOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csvOptionActionPerformed

    private void modelSavePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelSavePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelSavePathActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        GenerateStatements gs = GenerateStatements.getInstance();
        //gs.init(new File(pathTextFromMain.getText()));
        //gs.printNLStatements();
        System.out.println("from text: " + pathTextFromMain.getText());
        gs.generateStatementsFromAxioms(new File(pathTextFromMain.getText()));
        
        
        if(csvOption.isSelected()){
            gs.outputAsCSVFile(this.pathTextExportFromMain.getText());
        }
        else{
            gs.outputAsExcel(this.pathTextExportFromMain.getText());
        }
        
        JOptionPane.showMessageDialog(null, "Generation completed");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckLLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckLLMActionPerformed
        // TODO add your handling code here:
        
        if(ckLLM.isSelected()){
            llmPanel.setEnabled(true);
            this.ckLLMFactChecking.setEnabled(true);
            this.ckLLMRefinement.setEnabled(true);
        }
        else{
            llmPanel.setEnabled(false);
            this.ckLLMFactChecking.setEnabled(false);
            this.ckLLMRefinement.setEnabled(false);
        }
        
    }//GEN-LAST:event_ckLLMActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        LLMConfiguration llm_config = LLMConfiguration.getInstance();
        
        //Map<String, String> collectLLMList = llm_config.collectLLMList();
        
        //LLMURLList llm_list_instance = LLMURLList.getInstance();
        
        llmList = llm_config.collectLLMList();
        
        System.out.println(llmList.size() + " is the size of llmList");
        
        int i=0;
        for(var entry : llmList.entrySet()){
            
            llm_list.insertElementAt(entry.getKey(), i);
            
        }
        
        
        //this.llm_list.insertElementAt("test 1", 0);
        //llm_list.insertElementAt("test 2", 1);
        
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
         
            
            //UIManager.setLookAndFeel( new FlatDarkLaf() );
            
            UIManager.setLookAndFeel(new FlatLightLaf());
            
            
            
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(HootationUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HootationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckLLM;
    private javax.swing.JCheckBox ckLLMFactChecking;
    private javax.swing.JCheckBox ckLLMRefinement;
    private javax.swing.JRadioButton csvOption;
    private javax.swing.JRadioButton excelOption;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel llmPanel;
    private javax.swing.JList<String> lstLLM;
    private javax.swing.ButtonGroup modeldownloadOption;
    private javax.swing.ButtonGroup outputOptions;
    private javax.swing.JTextArea outputPanel;
    private javax.swing.JPanel panelHootation;
    private javax.swing.JPanel panelLLMConfiguration;
    private javax.swing.JPanel panelLLMDownload;
    private javax.swing.JTextField pathTextExportFromMain;
    private javax.swing.JTextField pathTextFromMain;
    private javax.swing.JButton saveToButtonFromMain;
    private javax.swing.JButton selectButtonFromMain;
    // End of variables declaration//GEN-END:variables
}
